First Real Commit
urospetrovic34/zadatak1-profile-card pull request #1
Opened 2021-09-10 14:22 UTC by urospetrovic34

2021-09-13 07:59 UTC, sbozic85 commented on .vscode/settings.json
> +    "liveServer.settings.port": 5501
Folderi tipa .vscode ili node_modules treba da se stave u .gitignore fajl. Nema potrebe da idu na repozitorijum

2021-09-13 08:00 UTC, sbozic85 commented on style.css
> +@import url('https://fonts.googleapis.com/css2?family=Kumbh+Sans&display=swap');
U style-guide.md kazu da treba i font-weight 700 da se koristi. Moras prvo da ga importujes pa onda i da ga upotrebis u CSS-u

2021-09-13 08:06 UTC, sbozic85 commented on style.css
> +    z-index:999;
Generalno, moja preporuka je da krenes sa mnogo manjim z-indexom, najmanjim mogucim (npr. z-index: 2). Ovo je vazno na vecim projektima. Takodje, trebalo bi i tom elementu dati makar position: relative, u suprotnom moze doci do nekih bagova

2021-09-13 08:08 UTC, sbozic85 requested changes
Pogledaj dizajn za manje ekrane i odradi i taj deo, trenutno to fali

2021-09-13 08:47 UTC, sbozic85 commented on style.css
> +        width:330px;
Urose imas ogroman vertikalan i horizontalan skrol na mobilnim telefonima. To ne treba tako da se vidi. Polako, ne moras i ne treba nigde da zuris, prodji jos jednom kroz CSS i ispravi to
![Screenshot_1](https://user-images.githubusercontent.com/90195863/133053105-1dacb73f-5c0f-4b29-9548-41be54dd834a.jpg)

2021-09-13 09:17 UTC, urospetrovic34 commented
Dodao sam na html takođe opciju overflow: hidden

2021-09-14 07:22 UTC, sbozic85 commented on index.html
> +                <p><span style="color:gray;font-size: 14px;">London</span></p>
Ne moras da pravis nove commitove, ovo je generalno ok, ali moja sugestija je da ne koristis inline CSS, osim u nekim situacijama kada je bas apsolutno neophodno, a ovde to nije slucaj

2021-09-14 07:23 UTC, sbozic85 approved these changes

2021-09-14 07:23 UTC, merged